# PYTHON LIBRARIES for data science


- numpy
- pandas
- matplot library

In [4]:
# numpy-used to create the multidimensional array
import numpy as np 
np.__version__


'1.16.4'

In [2]:
# array creation in numpy
np.array([1,2,3,4]) # using lists


array([1, 2, 3, 4])

In [3]:
np.array((1,2,3,4)) # using tupple

array([1, 2, 3, 4])

In [4]:
np.array([[1,2,3],[4,5,6]]) # multi dimesional

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
p=np.array([[[[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]]]]) 
print(p)
print(p.ndim)# dimension of the array using square brackets
print(p.size)# number of elements in the array
print(p.shape)# dim,row,coloum, after three it will add ones
print(p.dtype)# it shows data elements type
print(p.itemsize)# it shows the size of the item present in array


[[[[[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [10 11 12]
    [13 14 15]]]]]
5
15
(1, 1, 1, 5, 3)
int32
4


# array range using arange(array range)

In [7]:
print(np.arange(1,10)) # dynamic array
print(np.arange(10))# starts from zero
print(np.arange(1,10,2))# alternate numbers
print(np.arange(9,0,-2))# in reverse order
print(np.arange(24).reshape(3,8))# to arrange elements into dimensions of required (rows:coloum) 


[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[9 7 5 3 1]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [11]:
# linspace()
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
# to print random numbers in array
#print(np.random.randint(1,10,5).reshape(5,1))
print(np.random.randint(1,10,(3,3)))

[[6 2 1]
 [3 2 4]
 [9 3 8]]


In [24]:
# to print normal distribution values randomly
print(np.random.randn(3))
print(np.random.randn(3,2))
print(np.random.random((3,2)))

[-0.55445209  0.41909545 -0.78991789]
[[-0.32027459  0.01703317]
 [-1.19592629  0.65449965]
 [-0.1010768   1.32547068]]
[[0.49045875 0.84224792]
 [0.24122404 0.27354659]
 [0.27323228 0.46306158]]


In [18]:
# array initialisation
#'''- np.ones()
#- np.zeros()
#- np.diag()
#- np.full()'''

o=np.ones((2,3,4))
u=np.zeros((2,3,4))
e=np.diag((2,3,4))
r=np.full((3,3),4,)
print(o)
print(u)
print(r)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]


# index slicing in arrays

In [20]:
a=np.arange(20)
print(a)
print(a[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [49]:
q=(np.arange(24).reshape(3,8))
r=(q[::-1])
print(q)
print(q[1:4:2])#alternate rows


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 8  9 10 11 12 13 14 15]]


In [41]:
 print(q[1:3,2:3])# ending point +1 should give

[[10]
 [18]]


In [48]:
e=(q[1:4])
print(e[::-1])
print(e)

[[16 17 18 19 20 21 22 23]
 [ 8  9 10 11 12 13 14 15]]
[[ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [51]:
b=(np.arange(0,25).reshape(5,5))
print(b)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [53]:
x=b[1:5:2,1:5:2]
print(x)

[[ 6  8]
 [16 18]]


In [55]:
b[2:5,3:5]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [87]:
c=b[1:3,3:5]
print(c)
h=c[0,0]
f=c[1,1]
print(h)
print(f)
li=[]
li.append(h)
li.append(f)
li

[[ 8  9]
 [13 14]]
8
14


[8, 14]

In [89]:
b[[1,2],[3,4]]


array([ 8, 14])

# pandas

In [90]:
import pandas as pa


- series 
- data frames 


In [92]:
pa.__version__

'0.24.2'

In [94]:
pa.Series([1,2,3,4,5],index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [107]:
# using both pandas and numpy
#x=np.arange(10)
#y=pa.Series(x)
#print(y)
pa.Series((np.arange(1,6)),index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: int32

In [108]:
dates=pa.date_range('24-01-2020','31-01-2020')
dates

DatetimeIndex(['2020-01-24', '2020-01-25', '2020-01-26', '2020-01-27',
               '2020-01-28', '2020-01-29', '2020-01-30', '2020-01-31'],
              dtype='datetime64[ns]', freq='D')

In [116]:
dates=pa.date_range('2020-01-24','2020-01-31')
dates

DatetimeIndex(['2020-01-24', '2020-01-25', '2020-01-26', '2020-01-27',
               '2020-01-28', '2020-01-29', '2020-01-30', '2020-01-31'],
              dtype='datetime64[ns]', freq='D')

In [117]:
dates=pa.date_range('24-01-2020',periods=4)
dates

DatetimeIndex(['2020-01-24', '2020-01-25', '2020-01-26', '2020-01-27'], dtype='datetime64[ns]', freq='D')

### data frames

In [122]:
sm={'name':['a','b','c','d','e'],
    'marks':[10,20,30,40,50],
    'subject':['c','c++','java','python','.net',],
    'cgpa':[9.0,10,10,9.9,9.8]
   }
sm
pa.DataFrame(sm,index=['a','b','c','d','e'])

name  marks subject  cgpa
a    a     10       c   9.0
b    b     20     c++  10.0
c    c     30    java  10.0
d    d     40  python   9.9
e    e     50    .net   9.8

In [126]:
# read a csv file
data=pa.read_csv('Lifeexpectancy.csv')
data


population  fertility    HIV        CO2  BMI_male      GDP  BMI_female  \
0     34811059.0       2.73   0.10   3.328945  24.59620  12314.0    129.9049   
1     19842251.0       6.43   2.00   1.474353  22.25083   7103.0    130.1247   
2     40381860.0       2.24   0.50   4.785170  27.50170  14646.0    118.8915   
3      2975029.0       1.40   0.10   1.804106  25.35542   7383.0    132.8108   
4     21370348.0       1.96   0.10  18.016313  27.56373  41312.0    117.3755   
5      8331465.0       1.41   0.30   8.183160  26.46741  43952.0    124.1394   
6      8868713.0       1.99   0.10   5.109538  25.65117  14365.0    128.6024   
7       348587.0       1.89   3.10   3.131921  27.24594  24373.0    124.3862   
8    148252473.0       2.38   0.06   0.319161  20.39742   2265.0    125.0307   
9       277315.0       1.83   1.30   6.008279  26.38439  16075.0    126.3940   
10     9526453.0       1.42   0.20   6.488174  26.16443  14488.0    129.7968   
11    10779155.0       1.82   0.20   9.797337  26.75915  41641.0    121.8227   
12      306165.0       2.91   2.40   1.360126  27.02255   8293.0    120.9224   
13     8973525.0       5.27   1.20   0.537539  22.41835   1646.0    130.2723   
14      694990.0       2.51   0.20   0.601210  22.82180   5663.0    125.1258   
15     9599916.0       3.48   0.20   1.431829  24.43335   5066.0    122.4155   
16     1967866.0       2.86  24.90   2.547205  22.12984  13858.0    133.1307   
17   194769696.0       1.90   0.45   2.023773  25.78623  13906.0    124.8745   
18     7513646.0       1.43   0.10   6.690139  26.54286  15368.0    128.4721   
19    14709011.0       6.04   1.20   0.109419  21.27157   1358.0    130.6651   
20     8821795.0       6.48   3.50   0.031389  21.50291    723.0    134.1955   
21    13933660.0       3.05   0.60   0.287547  20.80496   2442.0    117.5528   
22    19570418.0       5.17   5.30   0.295542  23.68173   2571.0    127.2823   
23    33363256.0       1.68   0.20  16.350399  27.45210  41468.0    118.0571   
24    11139740.0       6.81   3.40   0.047839  21.48569   1753.0    127.8640   
25    16645940.0       1.89   0.40   4.240259  27.01542  18698.0    125.5417   
26    44901660.0       2.43   0.50   1.476092  24.94041  10489.0    124.0235   
27      665414.0       5.05   0.06   0.178853  22.06131   1440.0    132.1354   
28     3832771.0       5.10   3.50   0.384220  21.87134   5022.0    131.6935   
29     4429506.0       1.91   0.30   1.911933  26.47897  12219.0    121.3500   
..           ...        ...    ...        ...       ...      ...         ...   
109    9109535.0       1.41   0.10   5.271223  26.51495  12522.0    130.3755   
110    5521838.0       5.13   1.60   0.118256  22.53139   1289.0    134.7160   
111    4849641.0       1.28   0.10   4.114441  23.83996  65991.0    121.1736   
112    5396710.0       1.31   0.06   6.901654  26.92717  24670.0    129.5280   
113    2030599.0       1.43   0.06   8.511828  27.43983  30816.0    129.9231   
114    9132589.0       7.06   0.60   0.068219  21.96917    615.0    131.5318   
115   50348811.0       2.54  17.90   9.427960  26.85538  12263.0    130.9949   
116   45817016.0       1.42   0.40   7.293089  27.49975  34676.0    122.0453   
117   19949553.0       2.32   0.06   0.580791  21.96671   6907.0    124.8615   
118   34470138.0       4.79   1.00   0.382118  22.40484   3246.0    129.7199   
119     506657.0       2.41   1.00   4.741140  25.49887  13470.0    124.6358   
120    1153750.0       3.70  25.90   0.949861  23.16969   5887.0    131.8793   
121    9226333.0       1.92   0.10   5.315688  26.37629  43421.0    122.9473   
122    7646542.0       1.47   0.40   5.333058  26.20195  55020.0    119.6465   
123    7254072.0       3.70   0.20   0.453168  23.77966   2001.0    129.9657   
124   42844744.0       5.54   5.80   0.154673  22.47792   2030.0    130.8328   
125   66453255.0       1.48   1.30   3.835102  23.00803  12216.0    120.4969   
126    6052937.0       4.88   3.20   0.251983  21.87875   1219.0    131.0248   
127   

In [128]:
data.shape  #size

(139, 10)

In [133]:
data.head()#default top 5
data.tail()# default from bottom top 5
data.sample(3)# default one will come randomly

population  fertility  HIV        CO2  BMI_male      GDP  BMI_female  \
90   4285380.0       2.12  0.1   8.009084  27.76893  32122.0    118.7421   
18   7513646.0       1.43  0.1   6.690139  26.54286  15368.0    128.4721   
89  16519862.0       1.77  0.2  10.533028  26.01541  47388.0    121.6950   

    life  child_mortality                 Region  
90  80.2              6.4    East Asia & Pacific  
18  73.2             13.7  Europe & Central Asia  
89  80.3              4.8  Europe & Central Asia

In [138]:
data.columns#gives about the coloums information
data.index# gives the information about the indexs
data.dtypes

population         float64
fertility          float64
HIV                float64
CO2                float64
BMI_male           float64
GDP                float64
BMI_female         float64
life               float64
child_mortality    float64
Region              object
dtype: object

In [140]:
data.describe()# its mean std min min will come

population   fertility         HIV         CO2    BMI_male  \
count  1.390000e+02  139.000000  139.000000  139.000000  139.000000   
mean   3.549977e+07    3.005108    1.915612    4.459874   24.623054   
std    1.095121e+08    1.615354    4.408974    6.268349    2.209368   
min    2.773150e+05    1.280000    0.060000    0.008618   20.397420   
25%    3.752776e+06    1.810000    0.100000    0.496190   22.448135   
50%    9.705130e+06    2.410000    0.400000    2.223796   25.156990   
75%    2.791973e+07    4.095000    1.300000    6.589156   26.497575   
max    1.197070e+09    7.590000   25.900000   48.702062   28.456980   

                 GDP  BMI_female        life  child_mortality  
count     139.000000  139.000000  139.000000       139.000000  
mean    16638.784173  126.701914   69.602878        45.097122  
std     19207.299083    4.471997    9.122189        45.724667  
min       588.000000  117.375500   45.200000         2.700000  
25%      2899.000000  123.232200   62.200000         8.100000  
50%      9938.000000  126.519600   72.000000        24.000000  
75%     23278.500000  130.275900   76.850000        74.200000  
max    126076.000000  135.492000   82.600000       192.000000

In [142]:
data.isnull()# check whether is data empty or not
data.isnull().sum()#will check no of trues

population         0
fertility          0
HIV                0
CO2                0
BMI_male           0
GDP                0
BMI_female         0
life               0
child_mortality    0
Region             0
dtype: int64

In [149]:
data.dtypes.value_counts()# number of datatypes with its count
data.describe().loc[['min','max']]# to locate min and max functions

population  fertility    HIV        CO2  BMI_male       GDP  \
min  2.773150e+05       1.28   0.06   0.008618  20.39742     588.0   
max  1.197070e+09       7.59  25.90  48.702062  28.45698  126076.0   

     BMI_female  life  child_mortality  
min    117.3755  45.2              2.7  
max    135.4920  82.6            192.0

In [150]:
dcols=data.columns[data.dtypes=='float64']
dcols

Index(['population', 'fertility', 'HIV', 'CO2', 'BMI_male', 'GDP',
       'BMI_female', 'life', 'child_mortality'],
      dtype='object')

In [153]:
dcols.value_counts().sum()

9

In [157]:
play=pa.read_csv('googleplaystore.csv')


In [158]:
play.shape

(10841, 13)

In [159]:
play.head(6)

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   
5                         Paper flowers instructions  ART_AND_DESIGN     4.4   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   
5     167  5.6M      50,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   
5               Art & Design    March 26, 2017                 1.0   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up  
5    2.3 and up

In [160]:
play.tail(4)

App             Category  \
10837               Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                         Parkinson Exercices FR              MEDICAL   
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
10837     5.0       4                3.6M         100+  Free     0   
10838     NaN       3                9.5M       1,000+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating             Genres      Last Updated         Current Ver  \
10837       Everyone          Education      July 6, 2018                 1.0   
10838       Everyone            Medical  January 20, 2017                 1.0   
10839     Mature 17+  Books & Reference  January 19, 2015  Varies with device   
10840       Everyone          Lifestyle     July 25, 2018  Varies with device   

              Android Ver  
10837          4.1 and up  
10838          2.2 and up  
10839  Varies with device  
10840  Varies with device

In [161]:
play.sample(10)

App       Category  \
543                                  CMB Free Dating App         DATING   
7299                                 Best CG Backgrounds         FAMILY   
4200                                                H TV         FAMILY   
7136                                             CB News         FAMILY   
388                                  Calls & Text by Mo+  COMMUNICATION   
10369  FG. Chic - House Lounge Musique - Radios de Fr...         FAMILY   
5692                         Job'Of - Emploi au Cameroun       BUSINESS   
9277                         EF English Live for tablets         FAMILY   
9430                                         Egg for Pou         FAMILY   
6274                                            BI-LO Rx      LIFESTYLE   

       Rating Reviews                Size    Installs  Type Price  \
543       4.0   48845                 40M  1,000,000+  Free     0   
7299      3.6       8                3.7M        500+  Free     0   
4200      4.3  103064                5.6M  5,000,000+  Free     0   
7136      5.0       7                 20M         50+  Free     0   
388       4.2   83239                 14M  5,000,000+  Free     0   
10369     NaN       1                6.5M         50+  Free     0   
5692      4.1     294                9.8M     10,000+  Free     0   
9277      3.1    1242                 14M     50,000+  Free     0   
9430      3.0   59096  Varies with device  5,000,000+  Free     0   
6274      3.9      77  Varies with device     10,000+  Free     0   

      Content Rating         Genres        Last Updated         Current Ver  \
543       Mature 17+         Dating      August 1, 2018         4.19.0.2320   
7299        Everyone  Entertainment        May 20, 2018                 8.0   
4200        Everyone  Entertainment        July 5, 2018               4.6.2   
7136        Everyone      Education  September 10, 2016               1.2.0   
388         Everyone  Communication      April 19, 2018               3.0.4   
10369       Everyone  Entertainment        June 9, 2018                 1.0   
5692        Everyone       Business        July 5, 2018               4.1.2   
9277        Everyone      Education      April 24, 2018               1.7.0   
9430        Everyone         Casual  September 14, 2017  Varies with device   
6274        Everyone      Lifestyle      March 26, 2018  Varies with device   

              Android Ver  
543            4.4 and up  
7299         4.0.3 and up  
4200         2.3.3 and up  
7136           4.1 and up  
388            4.0 and up  
10369          4.2 and up  
5692           4.0 and up  
9277           4.4 and up  
9430         4.0.3 and up  
6274   Varies with device

In [163]:
play.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [164]:
play.dtypes.value_counts()

object     12
float64     1
dtype: int64

In [175]:
play.dtypes.value_counts().sum()

13

In [169]:
play.describe()

Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [190]:
play.describe().loc[['mean','count','std','25%']]

Rating
mean      4.193338
count  9367.000000
std       0.537431
25%       4.000000

In [173]:
play.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [189]:
dcols=play.columns[play.dtypes=='float64']
p=dcols
print(p)
dcols1=play.columns[play.dtypes=='object']
print(dcols1)


Index(['Rating'], dtype='object')
Index(['App', 'Category', 'Reviews', 'Size', 'Installs', 'Type', 'Price',
       'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')


In [187]:
play[dcols].nunique()

Rating    40
dtype: int64

In [188]:
play[dcols1].nunique()

App               9660
Category            34
Reviews           6002
Size               462
Installs            22
Type                 3
Price               93
Content Rating       6
Genres             120
Last Updated      1378
Current Ver       2832
Android Ver         33
dtype: int64